department-app/views/view_departments.py
from flask import Blueprint, render_template, jsonify, request, url_for, redirect
import logging
from service.crud import add_department, get_departments, get_department, del_department, put_department
from .forms import DepartmentForm
logging.basicConfig(filename="departments_log.log", level=logging.WARNING)
logger = logging.getLogger('dep')
from  datetime import datetime

# from rest.checkers import department_check
view_departments_blueprint = Blueprint('view_departments', __name__, template_folder='templates')


@view_departments_blueprint.route('/')
def departments_list():
    """
    Show list of departments
    :return:
    """
    departments = get_departments()
    return render_template('departments.html', departments=departments)


@view_departments_blueprint.route('/<int:id_dept>')
def department_item(id_dept):
    department = get_department(id_dept)
    return render_template('department.html', department=department)


@view_departments_blueprint.route('/create', methods=['GET', 'POST'])
def create_department():
    form = DepartmentForm()
    if form.validate_on_submit():
        title = form.title.data
        id_dept = add_department(title)
        log_msg = f'dep {id_dept}, {title}, created : {datetime.now()}'
        logger.warning(log_msg)
        return redirect(url_for('view_departments.department_item', id_dept=id_dept))
    return render_template('department_create.html', form=form)


@view_departments_blueprint.route('/delete/<int:id_dept>')
def delete_department(id_dept):
    deleted = del_department(id_dept)
    if deleted:
        return redirect(url_for('view_departments.departments_list'))
    else:
        item = 'employee'
        return render_template('not_existed.html', item=item)


@view_departments_blueprint.route('/edit/<int:id_dept>', methods=["GET", "POST"])
def edit_department(id_dept):
    form = DepartmentForm()
    department = get_department(id_dept)
    if form.validate_on_submit():
        title = form.title.data
        put_department(id_dept, title)
        return redirect(url_for('view_departments.department_item', id_dept=id_dept))
    return render_template('department_edit.html', form=form, department=department)



# put_department

department-app/views/view_employees.py
from flask import Blueprint, render_template, url_for, redirect
from service.crud import add_employee, get_employees, get_employee, del_employee, put_employee
from datetime import date, datetime
from .forms import EmployeeForm, BirthDateIntervalForm, BirthDateForm
from service.checkers import is_in_department
import logging
logger = logging.getLogger('empl')

view_employees_blueprint = Blueprint('view_employees', __name__, template_folder='templates')


@view_employees_blueprint.route('/', methods=['GET', 'POST'])
def employees_list():
    """
    show list of employees
    :return: list of employees
    """
    employees = get_employees()
    form1 = BirthDateForm()
    form2 = BirthDateIntervalForm()
    if form1.validate_on_submit() and form1.birthday.data:
        dates = form1.birthday.data.year, form1.birthday.data.month, form1.birthday.data.day, form1.birthday.data.year, form1.birthday.data.month, form1.birthday.data.day
        employees = get_employees(dates)
        temp_form = form1
        return render_template('employees.html', employees=employees, form1=temp_form, form2=form2)

    if form2.validate_on_submit() and form2.start_date.data and form2.end_date.data:
        dates = form2.start_date.data.year, form2.start_date.data.month, form2.start_date.data.day, form2.end_date.data.year, form2.end_date.data.month, form2.end_date.data.day
        employees = get_employees(dates)
        return render_template('employees.html', employees=employees, form1=form1, form2=form2)
    return render_template('employees.html', employees=employees, form1=form1, form2=form2)


@view_employees_blueprint.route('/<int:id_empl>')
def employee_item(id_empl):
    """
    returns employee by id
    :param id_empl:
    :return:
    """
    employee = get_employee(id_empl)
    return render_template('employee.html', employee=employee)


@view_employees_blueprint.route('/create', methods=['GET', 'POST'])
def create_employee():
    """
    create employee with name, salary and department id
    :return:
    """
    form = EmployeeForm()
    if form.validate_on_submit():
        name = form.name.data
        salary = form.salary.data
        department = form.department.data
        if not is_in_department(department):
            item = 'department'
            return render_template('not_existed.html', item=item)
        birthday = date(form.year.data, form.month.data, form.day.data)
        id_empl = add_employee(name, salary, birthday, department)
        log_msg = f'empl {department}, {name}, created : {datetime.now()}'
        logger.warning(log_msg)
        return redirect(url_for('view_employees.employee_item', id_empl=id_empl))
    return render_template('employee_create.html', form=form)


@view_employees_blueprint.route('/delete/<int:id_empl>')
def delete_employee(id_empl):
    """
    delete employee by id
    :param id_empl:
    :return:
    """
    deleted = del_employee(id_empl)
    if deleted:
        return redirect(url_for('view_employees.employees_list'))
    else:
        item = 'employee'
        return render_template('not_existed.html', item=item)


@view_employees_blueprint.route('/edit/<int:id_empl>', methods=['GET', 'POST'])
def edit_employee(id_empl):
    """
    employee by id
    :param id_empl:
    :return:
    """
    form = EmployeeForm()
    employee = get_employee(id_empl)
    if form.validate_on_submit():
        name = form.name.data
        salary = form.salary.data
        department = form.department.data
        if not is_in_department(department):
            item = 'department'
            return render_template('not_existed.html', item=item)
        birthday = date(form.year.data, form.month.data, form.day.data)
        put_employee(id_empl, name, salary, birthday, department)
        return redirect(url_for('view_employees.employee_item', id_empl=id_empl))
    return render_template('employee_edit.html', form=form, employee=employee)

department-app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">HOME</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('view_departments.departments_list')}}">Departments <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('view_employees.employees_list')}}">Employees <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('view_departments.create_department')}}">Add department <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('view_employees.create_employee')}}">Add employee <span class="sr-only"></span></a>
          </li>

        </ul>
      </div>
  </nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

department-app/templates/index.html
{% extends 'base.html' %}


{% block content %}
  <img src="../static/deer.jpg" alt="NEDHU">

{% endblock %}